name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write
    env:
      NODE_ENV: production
    steps:
        - uses: actions/checkout@v3

        - name: build
          run: |
            sudo apt-get update
            sudo apt-get install zip
            yarn install
            for theme in cubango zambezi bani
            do
              sed -i "s/${ARGUMENTS.theme}/$theme" ./src/index.js
              rm -rf build
              yarn build
              zip -r $theme.zip build
              echo "zip $theme.zip"
            done

        - name: deploy
          uses: prewk/s3-cp-action@v2
          with:
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            source: './build.zip'
            dest: ${{ secrets.BUCKET_URL }}
